package com.tds.persistence;

/**
 * A class to represent an event that was generated by the system.
 *
 * An event includes an ID, which identifies the type of the event, a timestamp, when the event was detected, GPS coordinates identifying the location where the event was detected and a filename if a picture was taken at the time of the event detection.
 *
 * @author Christian Bodler
 *
 */
public class TdsEvent {
    /** A number identifying the type of the event. */
    int eventId;
    /** A timestamp representing the time the event was detected. */
    long timestamp;
    /** GPS coordinates describing the location where the event was detected. */
    String gps;
    /** A path to an image file if a picture was taken at the time the event was detected. */
    String filename;

    /**
     * Creates a new event of the given type with the given timestamp, GPS coordinates and image location.
     *
     * @param eventId The type of the event.
     * @param timestamp The time when the event was detected.
     * @param gps A set of GPS coordinates where the event was detected.
     * @param filename The location of an image taken at the time the event was detected.
     */
    public TdsEvent(int eventId, long timestamp, String gps, String filename) {
        this.eventId = eventId;
        this.timestamp = timestamp;
        this.gps = gps;
        this.filename = filename;
    }

    @Override
    public String toString() {
        return "TdsEvent " + this.eventId;
    }

    /**
     * Returns the type of the event.
     *
     * @return The type of the event.
     */
    public int getEventId() {
        return eventId;
    }

    /**
     * Changes the event type.
     *
     * @param eventId The event type.
     */
    public void setEventId(int eventId) {
        this.eventId = eventId;
    }

    /**
     * Returns the time the event was detected at.
     *
     * @return The time the event was detected at.
     */
    public long getTimestamp() {
        return timestamp;
    }

    /**
     * Assigns a new detection time.
     *
     * @param timestamp The new detection time.
     */
    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Returns the GPS coordinates the event was detected at.
     *
     * @return The GPS coordinates the event was detected at.
     */
    public String getGps() {
        return gps;
    }

    /**
     * Assigns new GPS coordinates.
     *
     * @param gps The new GPS coordinates.
     */
    public void setGps(String gps) {
        this.gps = gps;
    }

    /**
     * Returns the location of the image taken when the event was detected.
     *
     * @return The location of the image taken when the event was detected.
     */
    public String getFilename() {
        return filename;
    }

    /**
     * Assigns a new image location.
     *
     * @param filename The new image location.
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

}
